name: Build & Test

on: [push, pull_request]

jobs:
  test:
    name: Test
    runs-on: ubuntu-20.04

    env:
      KONG_TEST_PG_DATABASE: kong
      KONG_TEST_PG_USER: kong
      KONG_TEST_DATABASE: postgres

    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_USER: kong
          POSTGRES_DB: kong
          POSTGRES_HOST_AUTH_METHOD: trust
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 5s --health-timeout 5s --health-retries 8

    steps:
      - name: Check out the source code
        uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: "Install Kong"
        run: |
          curl -Lo kong.2.5.0.amd64.deb "https://download.konghq.com/gateway-2.x-ubuntu-$(lsb_release -cs)/pool/all/k/kong/kong_2.5.0_amd64.deb"
          sudo dpkg -i kong.2.5.0.amd64.deb

      - name: "Install Node dependencies"
        run: npm install

      - name: Run Kong migrations
        run: kong migrations bootstrap --force

      - name: Look up build cache
        uses: actions/cache@v2
        id: cache-deps
        key: cache-key-v1
        with:
          path: |
            kong.*.deb
            node_modules/

      - name: Start Kong
        run: kong start

      - name: Run test
        run: test.sh
